# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyme', '0003_notification_messafe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messafe',
            new_name='message',
        ),
    ]
