# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
